import test from 'node:test';import assert from 'node:assert/strict';
import {createPlayer} from '../dist/state/player.js';import {applyEffects} from '../dist/engine/effect.js';import {materialize,matches,candidates} from '../dist/engine/event.js';import {eventById} from '../dist/data/events.js';import {advanceYear,choose} from '../dist/engine/year.js';import {annualFinance,netWorth} from '../dist/engine/finance.js';
const fixture=(city,career,extra=[])=>applyEffects(createPlayer({seed:'路线'+city,city}),[{type:'set',path:'age',value:25},{type:'education',level:5,major:'金融',text:'完成测试教育'},{type:'cash',value:2000000},...extra,{type:'career',id:career}],'路线准备');
function event(s,id,index){const data=eventById(id);assert.ok(matches(s,data.conditions),'硬条件不满足：'+id);const e=materialize(data,s);assert.ok(e,'事件不可用：'+id);return applyEffects(s,index===undefined?e.effects:e.options[index].effects,e.title);}
test('A 南通船厂→工伤→康复→转行苏州',()=>{let s=fixture('nantong','shipyard');const before=s.stats.health;s=event(s,'ship_injury');assert.equal(s.stats.health,before-60);assert.ok(s.tags.includes('长期伤病'));assert.ok(s.scheduled.some(q=>q.eventId==='recovery'));s=event(s,'recovery');s=event(s,'injury_transition',1);assert.equal(s.career,'sales');assert.equal(s.city,'suzhou');assert.equal(s.birthCity,'nantong');assert.equal(s.parents.length,2);});
test('B 杭州游戏策划→上海工作邀请',()=>{let s=fixture('hangzhou','game');s=applyEffects(s,[{type:'set',path:'careerYears',value:4}],'积累');const old=s.salary;s=event(s,'external_offer',0);assert.equal(s.city,'shanghai');assert.ok(s.salary>old);});
test('C 上海银行→购房→投资与年度房贷',()=>{let s=fixture('shanghai','bank');s=event(s,'house_buy',0);assert.equal(s.properties.length,1);s=event(s,'invest_choice',1);const loan=s.properties[0].loan;const f=annualFinance(s);s=applyEffects(s,f.effects,'年度结算');assert.ok(s.properties[0].loan<loan);assert.ok(s.investments.fund>0);assert.ok(Number.isFinite(netWorth(s)));});
test('D 成都说唱→声望与粉丝冲击→两年后压力',()=>{let s=fixture('chengdu','rapper',[{type:'hobby',key:'说唱/音乐创作',value:100}]);s=applyEffects(s,[{type:'set',path:'careerYears',value:3}],'积累');s=event(s,'viral');assert.ok(s.fans>=1580000);assert.ok(s.stats.reputation>=120);assert.ok(s.scheduled.some(q=>q.eventId==='fame_pressure'));});
test('E 武汉电竞社→电竞→迁居→退役转型',()=>{let s=createPlayer({seed:'竞技',city:'wuhan'});s=applyEffects(s,[{type:'set',path:'age',value:18},{type:'education',level:4,major:'机械',text:'职业教育'},{type:'hidden',key:'gaming',value:100},{type:'hobby',key:'游戏',value:100},{type:'club',name:'电竞社',hobby:'游戏',ability:'gaming'},{type:'career',id:'esports'},{type:'migrate',city:'hangzhou',reason:'青训签约'},{type:'set',path:'age',value:29}],'竞技路线');s=event(s,'sport_retirement',0);assert.equal(s.career,'game');assert.ok(s.tags.includes('竞技退役'));assert.ok(s.npcs.length);});
test('F 温州销售→创业→预约经营结果',()=>{let s=fixture('wenzhou','sales');s=event(s,'startup',0);assert.equal(s.career,'founder');assert.equal(s.counts.startups,1);assert.equal(s.businessType,'民营经济');assert.ok(s.scheduled.some(q=>q.eventId==='startup_result'));s=event(s,'startup_result');assert.ok(Number.isFinite(netWorth(s)));});
test('G 郑州电商→杭州→创业',()=>{let s=fixture('zhengzhou','ecommerce');s=applyEffects(s,[{type:'set',path:'careerYears',value:3}],'积累');s=event(s,'external_offer',0);assert.equal(s.city,'hangzhou');s=event(s,'startup',0);assert.equal(s.career,'founder');assert.equal(s.birthCity,'zhengzhou');});
test('十年前相识决定合作事件是否出现',()=>{let s=fixture('wenzhou','sales');s=applyEffects(s,[{type:'npc',id:'old',name:'老同学',value:10},{type:'set',path:'age',value:30}],'相识');assert.equal(materialize(eventById('friend_business'),s),null);s=applyEffects(s,[{type:'set',path:'age',value:40}],'十年后');assert.ok(materialize(eventById('friend_business'),s));});
test('赌场严格适龄且只通过事件参与，亏损留下长期影响',()=>{let s=createPlayer({seed:'赌场'});assert.ok(!candidates(s).some(c=>c.event.id==='casino'));assert.throws(()=>applyEffects(s,[{type:'gamble',level:4}],'未成年'));s=applyEffects(s,[{type:'set',path:'age',value:30},{type:'set',path:'cash',value:100},{type:'set',path:'rng',value:1000}],'准备');s=applyEffects(s,[{type:'gamble',level:4}],'参与');assert.equal(s.counts.gambles,1);assert.ok(s.hidden.addiction>0);assert.ok(s.memories.length>0);});
